### ISSUE TITLE
sign in from home page

### ISSUE THREAD

**Issue by mpetyx** [mpetyx/energagement#1]

**Comment by mpetyx** [comment]
nice nice!
can you paste a screenshot here @vasilikisv ?

**Comment by vasilikisv** [comment]
![sign in](https://cloud.githubusercontent.com/assets/11905307/8079535/d611744a-0f6d-11e5-91c1-ad1d7328f2f1.png)

**Comment by vasilikisv** [comment]
![home](https://cloud.githubusercontent.com/assets/11905307/8079542/e0fa03cc-0f6d-11e5-941d-fb830618c66e.png)

**Comment by vasilikisv** [comment]
![main](https://cloud.githubusercontent.com/assets/11905307/8079546/e65ceb4a-0f6d-11e5-9239-4068ac41eabe.png)

**Comment by vasilikisv** [comment]
Ό,τι δεν σου αρέσει πες μου! Τώρα θα αλλάξω το footer με τα δικά μας στοιχεία στο about και στο contact us.. Γενικά στο home τι να περιέχει η σελίδα; π.χ. καμιά περιγραφή της εφαρμογής και παρότρυνση για sign in/ sign up; @mpetyx
